version: '1'
services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  app:
    build: 
      context: ./app
      args:
          baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - kafka
      - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgo_consumer_service
      SPRING_DATASOURCE_USERNAME: ftgo_consumer_service_user
      SPRING_DATASOURCE_PASSWORD: ftgo_consumer_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
